version: '3'
services:
  timetracker:
    container_name: company_manager
    build:
      context: .
      dockerfile: company_manager.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgresdb


  postgresdb:
    image: postgres:latest
    env_file:
      - .env
    ports:
          - "5432:5432"
    volumes:
      - database-inf:/var/lib/postgresql/data/


volumes:
  database-inf:
